shunting-yard-rs-fork
Skarlett/shunting-yard-rs pull request #1
Opened 2022-06-30 15:34 UTC by jasonzou0

Previous implementation assumes '-' is always a binary operator but that assumption is broken for expressions like '-19+20'. This change fixes that by adding 0 as the left operand if '-' only has one (right) operand to work with.

Tested: expressions such as '-19' and '1+(-19+2*20)' now works correctly (but weren't before).

2022-07-03 17:42 UTC, Skarlett commented
Hey, great to see this is your first contribution!

Good catch on the bug! it does pass your test example. I followed up with a few more tests, and found that your patch does remedy some issues, but doesn't pass all test cases.

```
# with patch
-1.5 * -2 => -3.5
```

If you like, we can move this PR into a draft on a separate branch & debug the issue further together.

Please reach back and let me know so that you're included in the triage & restoration.

2022-07-03 21:04 UTC, Skarlett commented on demo.rs
> +		let result = if matches!(tok.token_type, Lexer::Minus) {
`matches!(expr, T(x) if <x>)` could be replaced with `if let Lexer::Minus = tok.token_type`

2022-07-03 21:07 UTC, Skarlett requested changes
I think we should target the `tokenize` function to include negative numbers instead of the evaluation function for this patch. 

Currently this patch doesn't pass the tests.

2022-07-06 00:18 UTC, jasonzou0 commented on demo.rs
> +		let result = if matches!(tok.token_type, Lexer::Minus) {
Thanks! Just applied that change in my own branch. I'm a complete n00b on both github (as well as for Rust). is there anything else that i should do regarding your other suggestion of committing this to another branch to debug together?

2022-07-06 01:22 UTC, jasonzou0 commented
> I think we should target the `tokenize` function to include negative numbers instead of the evaluation function for this patch.
> 
> Currently this patch doesn't pass the tests.

Yeah I agree. The tricky thing here is the ambiguity of intrepretation. As an example, consider the expression of '-1-2-3', and ask yourself which minus signs do you want to interpret as negative number and which one as actual minus sign? I see two ways:
1) add positional logic to only interpret the first one in a given sub-expression / expression as negative number
2) force all cases to be interpreted as negative numbers, so that the above expression essentially becomes (-1) + (-2) + (-3).

Any preference? 2) seems easier to me btw.

2022-07-06 12:22 UTC, Skarlett commented
I've appended a possible fix in: https://github.com/Skarlett/shunting-yard-rs/commit/549481ed47f5fadc9fe2464197c11c0259b0c6f0 which passes all tests.
 
If you can find any problems with this method, I'd love to hear it. 

> force all cases to be interpreted as negative numbers, so that the above expression essentially becomes (-1) + (-2) + (-3).

I do like this option as a thought experiment, but it'd require token injection, which may include adding an extra operator to the operator-stack which doesn't exist.

```rs
match char {
  '-' => { stack.push(Lexer::Add); /*write a flag to keep state in tokenize(..) */ }
}
```
I actually find this to be a bit undesirable, it maybe unclear for those who are looking at the code base.

```rs
match c {
    '-' => match acc.last() {
        Some(x) => match x.token_type {
          Lexer::Num | Lexer::ParamClose => Some(Lexer::Minus),
          
          // Negative number.
          _ => Some(Lexer::Num),
        }
        None => Some(Lexer::Num)
    },
    ...
}
```
https://github.com/Skarlett/shunting-yard-rs/commit/549481ed47f5fadc9fe2464197c11c0259b0c6f0

this fix works by checking if the previous item pushed onto the token's output is a number.

If the previous token was a number, or closing parenthesis then the current `-` symbol is meant to act an as operator.
If there is no previous token, or the token is an open parenthesis, then we include the current `-` as a numeric.

What's your thoughts on this? I believe this should work for any valid expression.

2022-07-06 13:03 UTC, closed without merging

2022-10-11 07:49 UTC, jasonzou0 commented
Yeah let’s do that.

On Sun, Jul 3, 2022 at 1:42 PM Lunarix ***@***.***> wrote:

> Hey, great to see this is your first contribution!
>
> Good catch on the bug! it does pass your test example. I followed up with
> a few more tests, and found that your patch does remedy some issues, but
> doesn't pass all test cases.
>
> # with patch
> -1.5 * -2 => -3.5
>
> If you like, we can move this PR into a draft on a separate branch & debug
> the issue further together.
>
> Please reach back and let me know so that you're included in the triage &
> restoration.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Skarlett/shunting-yard-rs/pull/1#issuecomment-1173142677>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNVTXA322MV53FYRYJC2WDVSHGH5ANCNFSM52JZITSQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>